---
title: "CNS 2022 Plots"
author: "Hyuna Cho"
date: "28/03/2022"
output: html_document
---

```{r Load in data}

rm(list = ls()) # clear environment

library(tidyverse)
library(data.table) # used extensively for data cleaning and analysis
library(pwr) # for power analyses

retrieval <- read.csv("../clean_scripts/Extra_retrieval.csv") # currently in the cleaned folder

retrieval <- as.data.table(retrieval)
retrieval[, HR := mean(correct), by = participant] # hit rate by participant
retrieval[, avg_mem := correct - HR, by = participant] # participant-corrected hit rate

```

```{r Create useful dataframes}

random = retrieval[condition == "random"] # random condition

software = retrieval[condition == "software"] # software condition

# useful for grabbing specific number of stimuli later
tmp_software <- separate(data = software,
                col = stimulus, sep = 1,
                into = c("letter", "number"))
tmp_software <- separate(data = tmp_software,
                col = number, sep = ".jpg",
                into = c("number", "jpg"))

```


# Power analysis

```{r Paired Cohen's D of Study 2 subj}

# get avg correct/accuracy rates by participant
all_HR <- retrieval[,.(mean = mean(correct)), 
                               by = .(condition, participant, old_object_condition)]

# RANDOM condition 3 vs 1 exposures (paired Cohen's D)
all_cohensd_random_HR = cohen.d(
  all_HR[condition == "random" & old_object_condition == 3]$mean, 
  all_HR[condition == "random" & old_object_condition == 1]$mean, 
  paired = T) # 0.94

# SOFTWARE condition 3 vs 1 exposures (paired Cohen's D)
all_cohensd_software_HR = cohen.d(
  all_HR[condition == "software" & old_object_condition == 3]$mean, 
  all_HR[condition == "software" & old_object_condition == 1]$mean, 
  paired = T) # 0.86

```

```{r}
# Load in effect sizes

plot_ef = read.csv("plotef_full.csv")

```


```{r Basic power analyses}

library(pwr)

# HOW MANY SUBJ ARE NEEDED?

# Random: at the effect size at 80 stim per group, we would need 6.7821 subj
pwr.t.test(n = NULL,
           d = plot_ef[group == "Random" & stimpergroup == 10]$mean, 
           sig.level = .05, 
           power = .8, 
           type = "paired")

# Software: at the effect size at 80 stim per group, we would need 4.939468 subj
pwr.t.test(n = NULL,
           d = plot_ef[group == "Software" & stimpergroup ==10]$mean, 
           sig.level = .05, 
           power = .8, 
           type = ("paired"))

# MINIMUM EFF SIZE TO DETECT AN EFFECT

# Random: with the subj we have in the random condition after cleaning (n=34), min eff size is .49
pwr.t.test(n = length(unique(random$participant)),
           d = NULL, 
           sig.level = .05, 
           power = .8, 
           type = "paired")

# Software: with the subj we have in the software (n=36), min eff size is .48
pwr.t.test(n = length(unique(software$participant)),
           d = NULL, 
           sig.level = .05, 
           power = .8, 
           type = "paired")


# HOW WELL POWERED ARE WE?

# Random: with the subj we have (n=34) and the eff size at 80 stim per group, we are fully powered
pwr.t.test(n = length(unique(random$participant)),
           d = plot_ef[group == "Random" & stimpergroup ==80]$mean, 
           sig.level = .05, 
           power = NULL, 
           type = "paired")

# Software: with the subj we have (n=36) and the eff size at 80 stim per group, we are fully powered
pwr.t.test(n = length(unique(software$participant)),
           d = plot_ef[group == "Software" & stimpergroup ==80]$mean, 
           sig.level = .05, 
           power = NULL, 
           type = "paired")

```



https://www.statmethods.net/stats/power.html
```{r Power graph from a website}

# Plot sample size curves for detecting correlations of
# various sizes.

library(pwr)

# range of effect sizes
d <- seq(.1,2.1,.01)
nd <- length(d)

# power values
p <- seq(.4,.9,.1)
np <- length(p)


# obtain sample sizes
samsize <- array(numeric(nd*np), dim=c(nd,np))
for (i in 1:np){
  for (j in 1:nd){
    result <- pwr.t.test(n = NULL, d = d[j],
                         sig.level = .05, power = p[i],
                         type = "two.sample",)
    samsize[j,i] <- ceiling(result$n)
  }
}


# set up graph
xrange <- range(d)
yrange <- round(range(samsize))
colors <- rainbow(length(p))

plot(xrange, c(0,200), type="n",
  xlab="Effect Size (d)",
  ylab="Sample Size (n)" )

# add power curves
for (i in 1:np){
  lines(d, samsize[,i], type="l", lwd=2, col=colors[i])
}

abline(h=0, v=plot_ef[group == "Software" & stimpergroup ==20]$mean, lty=5, col="#674AEE")
abline(h=0, v=plot_ef[group == "Random" & stimpergroup ==20]$mean, lty=5, col="#6AA84F")

theme_minimal()

# add annotation (grid lines, title, legend)
abline(v=0, h=seq(0,yrange[2],50), lty=2, col="grey89")
abline(h=0, v=seq(xrange[1],xrange[2],.02), lty=2,
   col="grey89")
title("Sample Size Estimation for Correlation Studies\n
  Sig=0.05 (Two-tailed)")
legend("topright", title="Power", as.character(p),
   fill=colors)

# added for transparent bg
theme(
    panel.background = element_rect(fill="transparent"),
    plot.background = element_rect(fill="transparent", color = NA),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.background = element_rect(fill="transparent"),
    legend.box.background = element_rect(fill = "transparent")
  )


```

# Effect Size graphs

Load in the table with simulated effect sizes for random and the effect sizes for Software.Plot using a line graph.

```{r}

plot_ef = read.csv("../clean_scripts/plotef_full.csv")

ef_graph <- ggplot(plot_ef, aes(x = stimpergroup, y = mean, color = group)) +
  geom_line() +
  ylab("effect size") +
  geom_errorbar(aes(ymin=CI_lower, ymax=CI_upper), width = .7) +
  theme(
      panel.background = element_rect(fill="transparent"),
      plot.background = element_rect(fill="transparent", color = NA),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.background = element_rect(fill="transparent"),
      legend.box.background = element_rect(fill = "transparent")
    )

ef_graph1 <- ggplot(plot_ef, aes(x = stimpergroup, y = mean, color = group, fill=group)) +
  geom_smooth(formula = y ~ log(x), stat="smooth", se=T) +
  ylab("effect size") +
  # geom_errorbar(aes(ymin=CI_lower, ymax=CI_upper), width = .7) +
  theme(
      panel.background = element_rect(fill="transparent"),
      plot.background = element_rect(fill="transparent", color = NA),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.background = element_rect(fill="transparent"),
      legend.box.background = element_rect(fill = "transparent")
    ) +
  scale_color_manual(values = c("#6AA84F", "#674AEE")) +
  scale_fill_manual(values = c("#6AA84F", "#674AEE"))


```




